Allow to configure aquire timer scheduler
reactor/reactor-pool pull request #158
Opened 2022-05-03 13:40 UTC by pderop

This is the PR to allow to configure the reactor-pool with a custom user timer service that can be used for pending acquisitions (thanks a lot to Simon for the help).

@simonbasle, **please do not merge for the moment**, because Violeta wants to investigate the timer issue before merging anything. And there is still the documentation to update; so, please do not review for the moment.

thanks !

2022-06-02 17:29 UTC, violetagg requested changes
Please fix the copyright end year

I'm wondering which is more correct

`acquireTimer` or `pendingAcquireTimer`, because this timer is not applied to the whole acquire operation but only while the `Borrower` is in the pending queue.

2022-06-02 17:29 UTC, violetagg commented on src/main/java/reactor/pool/AbstractPool.java
> +					timeoutTask = this.pool.config().acquireTimer().apply(this, acquireTimeout);
Please remove the unused imports

```
import java.util.concurrent.TimeUnit;
import reactor.core.scheduler.Schedulers;
```

2022-06-02 17:29 UTC, violetagg commented on src/main/java/reactor/pool/DefaultPoolConfig.java
> +							 boolean isIdleLRU) {
Please remove the formatting change

2022-06-02 17:29 UTC, violetagg commented on src/test/java/reactor/pool/PoolBuilderTest.java
> +import java.util.concurrent.CountDownLatch;
Please remove the unused import

2022-06-07 11:48 UTC, pderop commented
@simonbasle ,

Hi Simon, can you confirm if you are ok with the suggestions made by Violeta so I can update this PR ?
thanks.

2022-06-08 09:46 UTC, simonbasle commented
`pendingAcquireTimer` sounds good. note that in the interface, `acquire(Duration)` javadoc explains that the ttl only applies to the time during which the borrower is in pending state:

```

but since the configuration and its documentation is detached from this method and typically used in different places, it is a good thing to insist on that "pending only" aspect.

+1 on all other requested changes
	 /* Manually acquire a {@code POOLABLE} from the pool upon subscription and become responsible for its release.
	 * The provided {@link Duration} acts as a timeout that only applies if the acquisition is added to the pending
	 * queue, i.e. there is no idle resource and no new resource can be created currently, so one needs to wait
	 * for a release before a resource can be delivered. For a timeout that covers both this pending case and the
	 * time it would take to allocate a new resource, simply apply the {@link Mono#timeout(Duration)} operator to
	 * the returned Mono. For a timeout that only applies to resource allocation, build the pool with the standard
	 * {@link Mono#timeout(Duration)} operator chained to the {@link PoolBuilder#from(Publisher) allocator}.
	 * /
```

2022-06-08 09:55 UTC, simonbasle requested changes
suggesting improvements to the javadoc. please check the formatting / length / links 😉

2022-06-08 09:55 UTC, simonbasle commented on src/main/java/reactor/pool/PoolBuilder.java
> +	 * provided function.
```suggestion
	 * Define how timeouts are scheduled when a {@link Pool#acquire(Duration)} call is made and the acquisition is pending.
	 * i.e. there is no idle resource and no new resource can be created currently, so a timeout is scheduled using the
	 * provided function.
```

2022-06-08 09:55 UTC, simonbasle commented on src/main/java/reactor/pool/PoolConfig.java
> +	 * returned function.
```suggestion
	 * The function that defines how timeouts are scheduled when a {@link Pool#acquire(Duration)} call is made and the acquisition is pending.
	 * i.e. there is no idle resource and no new resource can be created currently, so a timeout is scheduled using the
	 * returned function.
```

2022-06-08 10:59 UTC, violetagg approved these changes

2022-06-08 11:54 UTC, pderop commented
@simonbasle , can you please re-review , then can you merge this PR ?
thanks !

2022-06-08 11:55 UTC, simonbasle approved these changes

2022-06-08 12:09 UTC, merged

2022-06-08 12:41 UTC, simonbasle commented
tested locally: `main` execution of japicmp vs 0.2.9-SNAPSHOT, with new constructor exclusion ✅